# Generated by Django 4.2.4 on 2023-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='member',
            name='ordering',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
