# Generated by Django 4.2.4 on 2023-08-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_options_member_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_bazar_done',
            field=models.BooleanField(default=False),
        ),
    ]
