# Generated by Django 4.2.4 on 2023-08-31 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_bazarlist_date_remove_fine_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 31)),
        ),
        migrations.AlterField(
            model_name='moneydeposit',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 31)),
        ),
    ]
