# Generated by Django 4.2.4 on 2023-08-31 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_fine_date_alter_moneydeposit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazarcost',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fine',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moneydeposit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
