# Generated by Django 4.2.4 on 2023-08-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_bazarcost_date_alter_fine_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazarcost',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fine',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='moneydeposit',
            name='date',
            field=models.DateField(),
        ),
    ]
