# Generated by Django 4.2.4 on 2023-09-02 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_bazarcost_date_alter_fine_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('morning', models.DecimalField(decimal_places=2, default=0.5, max_digits=8)),
                ('launch', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('dinner', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='meal',
            name='morning',
        ),
        migrations.AddField(
            model_name='meal',
            name='breakfast',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=8, verbose_name='সকাল'),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_continue',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 3)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dinner',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='রাত'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='launch',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='দুপুর'),
        ),
    ]
