# Generated by Django 4.2.4 on 2023-09-02 13:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_mealrequest_remove_meal_morning_meal_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazarcost',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
