# Generated by Django 4.2.4 on 2023-09-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_bazarcost_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealRequest',
        ),
    ]
