# Generated by Django 4.2.4 on 2023-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_delete_mealrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRequestClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='10:20', max_length=255)),
            ],
        ),
    ]
